apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: failover-agent
  namespace: kagent
  labels:
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: failover-agent
    app.kubernetes.io/version: 0.5.5
  annotations:
    meta.helm.sh/release-name: kagent
    meta.helm.sh/release-namespace: kagent
spec:
  description: "A resilient failover demo agent for testing blue/green switching and deployment strategies."
  modelConfig: default-model-config
  systemMessage: |
    You are a resilient failover demo agent. Your job is to test blue/green switching.
    
    ## Core Capabilities
    - Test blue/green deployment switching
    - Demonstrate failover scenarios
    - Validate deployment resilience
    - Provide insights on deployment strategies
    
    ## Available Tools
    You have access to Kubernetes tools to help with failover testing and blue/green deployments.
  
  tools:
    - type: McpServer
      mcpServer:
        toolServer: kagent-querydoc
        toolNames:
          - query_documentation
    - type: McpServer
      mcpServer:
        toolServer: kagent-tool-server
        toolNames:
          - k8s_get_resources
          - k8s_describe_resource
          - k8s_get_events
          - k8s_get_pod_logs
          - k8s_apply_manifest
          - k8s_create_resource
          - k8s_delete_resource
          - k8s_get_resource_yaml
          - k8s_patch_resource
          - k8s_label_resource
          - k8s_annotate_resource

  a2aConfig:
    skills:
      - id: blue-green-testing
        name: Blue/Green Deployment Testing
        description: "Test and validate blue/green deployment strategies, including traffic switching and rollback scenarios."
        tags:
          - blue-green
          - deployment
          - testing
          - failover
          - traffic-switching
        examples:
          - "Test a blue/green deployment switch for my application"
          - "Validate that my blue/green setup can handle failover scenarios"
          - "Help me set up a blue/green deployment test"
      
      - id: failover-validation
        name: Failover Validation
        description: "Validate system resilience and failover capabilities during deployment scenarios."
        tags:
          - failover
          - resilience
          - validation
          - testing
          - deployment
        examples:
          - "Test the failover capabilities of my deployment"
          - "Validate that my application can handle node failures"
          - "Check if my deployment strategy provides adequate resilience"
      
      - id: deployment-strategy-guidance
        name: Deployment Strategy Guidance
        description: "Provide guidance on deployment strategies, including blue/green, canary, and rolling updates."
        tags:
          - deployment
          - strategy
          - guidance
          - best-practices
          - blue-green
          - canary
        examples:
          - "What deployment strategy should I use for my application?"
          - "Compare blue/green vs canary deployment strategies"
          - "Help me choose the right deployment approach for zero-downtime updates"