apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: anthropic-claude
  namespace: kagent
spec:
  provider: Anthropic
  model: claude-sonnet-4-20250514
  apiKeySecret: kagent-anthropic
  apiKeySecretKey: ANTHROPIC_API_KEY
