apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: openai-sonnet
  namespace: kagent
spec:
  provider: OpenAI
  model: gpt-4.1-mini
  apiKeySecretRef: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
