apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: claude-sonnet
  namespace: kagent
spec:
  provider: Anthropic
  model: claude-3-5-sonnet-20241022
  apiKeySecretRef: kagent-anthropic
  apiKeySecretKey: ANTHROPIC_API_KEY
